#!/usr/local/bin/node

const repl = require('repl')
const read = require('fs').readFileSync
const brainfuck = require('./dist/brainfuck').exec

function usage() {
  console.log('Usage: main [mode] <file>')
  console.log('')
  console.log('  - modes: brainfuck')
}

function runExec(interpreter, file) {
  interpreter(read(file).toString())
}

function runRepl(interpreter) {
  repl.start({
    prompt: '> ',
    eval: function (cmd, ctx, file, cb) {
      var buff = ''

      interpreter(cmd, {
        write: function (str) {
          buff += str
        },

        done: function () {
          cb(null, buff)
        }
      })
    }
  });
}

function handle(interpreter) {
  if (process.argv[3]) {
    runExec(interpreter, process.argv[3])
  } else {
    runRepl(interpreter)
  }
}

switch (process.argv[2]) {
case 'brainfuck':
  handle(brainfuck)
  break

case '-h':
case '--help':
  usage()
  break

default:
  usage()
  process.exit(1)
}
