#!/usr/local/bin/node

const repl = require('repl')
const read = require('fs').readFileSync
const brainfuck = require('../dist/brainfuck').exec
const brainloller = require('../dist/brainloller').exec

function usage() {
  console.log('Usage: repl [mode] <file>')
  console.log('')
  console.log('  - modes: brainfuck')
  console.log('  - modes: brainloller')
}

function runExec(interpreter, file, processorFn) {
  var buff = []

  interpreter(processorFn(read(file).toString()), {
    write(str) {
      buff.push(str)
    },

    done() {
      if (buff.length) {
        console.log(buff.join(''))
      }
    }
  })
}

function runRepl(interpreter) {
  repl.start({
    prompt: '> ',
    eval: function (cmd, ctx, file, cb) {
      var buff = ''

      interpreter(cmd, {
        write: function (str) {
          buff += str
        },

        done: function () {
          cb(null, buff)
        }
      })
    }
  });
}

function handle(interpreter, processorFn) {
  if (process.argv[3]) {
    runExec(interpreter, process.argv[3], processorFn)
  } else {
    runRepl(interpreter)
  }
}

switch (process.argv[2]) {
case 'brainfuck':
  handle(brainfuck, (x) => x)
  break

case 'brainloller':
  handle(brainloller, (x) => JSON.parse(x))
  break

case '-h':
case '--help':
  usage()
  break

default:
  usage()
  process.exit(1)
}
